---Snowflake setup:

USE ROLE SYSADMIN;
create database if not exists llm_db;
use database llm_db;
create schema if not exists vllm_sch;
create schema if not exists mr_sch;

USE ROLE ACCOUNTADMIN;
CREATE ROLE IF NOT EXISTS LLM_ROLE;
GRANT ROLE LLM_ROLE to ROLE SYSADMIN;
GRANT CREATE COMPUTE POOL ON ACCOUNT TO ROLE LLM_ROLE;
GRANT BIND SERVICE ENDPOINT ON ACCOUNT TO ROLE LLM_ROLE;
GRANT USAGE ON DATABASE llm_db TO ROLE LLM_ROLE;
GRANT USAGE ON SCHEMA llm_db.vllm_sch TO ROLE LLM_ROLE;
GRANT CREATE TABLE ON SCHEMA llm_db.vllm_sch TO ROLE LLM_ROLE;
GRANT SELECT, INSERT, DELETE, TRUNCATE ON ALL TABLES IN SCHEMA llm_db.vllm_sch TO ROLE LLM_ROLE;
GRANT SELECT, INSERT, DELETE, TRUNCATE ON FUTURE TABLES IN SCHEMA llm_db.vllm_sch TO ROLE LLM_ROLE;
GRANT CREATE STAGE ON SCHEMA llm_db.vllm_sch TO ROLE LLM_ROLE;
GRANT CREATE FILE FORMAT ON SCHEMA llm_db.vllm_sch TO ROLE LLM_ROLE;
GRANT CREATE FUNCTION on SCHEMA llm_db.vllm_sch TO ROLE LLM_ROLE;
GRANT CREATE PROCEDURE on SCHEMA llm_db.vllm_sch TO ROLE LLM_ROLE;
GRANT CREATE IMAGE REPOSITORY ON SCHEMA llm_db.vllm_sch TO ROLE LLM_ROLE;
GRANT CREATE SERVICE ON SCHEMA llm_db.vllm_sch TO ROLE LLM_ROLE;
GRANT CREATE WAREHOUSE ON ACCOUNT TO ROLE LLM_ROLE;

use schema vllm_sch;
CREATE OR REPLACE NETWORK RULE allow_all_rule
MODE= 'EGRESS'
TYPE = 'HOST_PORT'
VALUE_LIST = ('0.0.0.0:443','0.0.0.0:80');

CREATE OR REPLACE EXTERNAL ACCESS INTEGRATION allow_all_integration
ALLOWED_NETWORK_RULES = (allow_all_rule)
ENABLED = true;


GRANT USAGE ON INTEGRATION allow_all_integration TO ROLE LLM_ROLE;
GRANT ROLE LLM_ROLE TO USER plakhanpal;


-- common setup
use role LLM_ROLE;
USE DATABASE llm_db;
USE SCHEMA vllm_SCH;
create image repository if not exists VLLM_IMAGE_REPO;
SHOW IMAGE REPOSITORIES IN SCHEMA;
create warehouse if not exists xsmall_wh;
create stage if not exists YAMLSPECS;