USE ROLE llm_role;
USE DATABASE llm_db;
USE SCHEMA vllm_sch;
use warehouse XSMALL_LLM_WH;
SHOW COMPUTE POOLS LIKE 'DOWNLOAD_MODEL_POOL';

CALL SYSTEM$GET_SERVICE_STATUS('DOWNLOAD_MODEL_SERVICE');
SELECT SYSTEM$GET_SERVICE_LOGS('DOWNLOAD_MODEL_SERVICE', 0, 'downloadmodel') as DOWNLOAD_MODEL_JOB_STATUS;

ls @models/;